
import { Service, ServiceCategory, City } from './types';

export const SUPPORTED_CITIES: City[] = [
  { id: 'bangalore', name: 'Bangalore', state: 'Karnataka', illustration: '🏰', lat: 12.9716, lng: 77.5946 },
  { id: 'mumbai', name: 'Mumbai', state: 'Maharashtra', illustration: '🎡', lat: 19.0760, lng: 72.8777 },
  { id: 'delhi', name: 'Delhi', state: 'Delhi', illustration: '🏛️', lat: 28.6139, lng: 77.2090 },
  { id: 'hyderabad', name: 'Hyderabad', state: 'Telangana', illustration: '🕌', lat: 17.3850, lng: 78.4867 },
  { id: 'kolkata', name: 'Kolkata', state: 'West Bengal', illustration: '🌉', lat: 22.5726, lng: 88.3639 },
  { id: 'pune', name: 'Pune', state: 'Maharashtra', illustration: '🎢', lat: 18.5204, lng: 73.8567 },
  { id: 'chennai', name: 'Chennai', state: 'Tamil Nadu', illustration: '🛕', lat: 13.0827, lng: 80.2707 },
  { id: 'jaipur', name: 'Jaipur', state: 'Rajasthan', illustration: '🐪', lat: 26.9124, lng: 75.7873 },
  { id: 'noida', name: 'Noida', state: 'Uttar Pradesh', illustration: '🏙️', lat: 28.5355, lng: 77.3910 },
  { id: 'gurgaon', name: 'Gurgaon', state: 'Haryana', illustration: '🏬', lat: 28.4595, lng: 77.0266 },
  { id: 'vijayawada', name: 'Vijayawada', state: 'Andhra Pradesh', illustration: '☸️', lat: 16.5062, lng: 80.6480 },
  { id: 'vishakapatnam', name: 'Vishakapatnam', state: 'Andhra Pradesh', illustration: '🌊', lat: 17.6868, lng: 83.2185 },
  { id: 'coimbatore', name: 'Coimbatore', state: 'Tamil Nadu', illustration: '🏭', lat: 11.0168, lng: 76.9558 },
  { id: 'mysore', name: 'Mysore', state: 'Karnataka', illustration: '👑', lat: 12.2958, lng: 76.6394 },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: '1',
    name: 'The Grand Ballroom',
    category: ServiceCategory.VENUE,
    price: 45000,
    rating: 4.8,
    reviewsCount: 124,
    location: 'Indiranagar',
    cityId: 'bangalore',
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&q=80&w=800',
    description: 'A luxurious ballroom perfect for weddings and large corporate events.',
    features: ['Valet Parking', 'AC Hall', 'Power Backup'],
    isAvailable: true
  },
  {
    id: '2',
    name: 'Marine Drive Shoots',
    category: ServiceCategory.PHOTOGRAPHY,
    price: 18000,
    rating: 4.9,
    reviewsCount: 142,
    location: 'Marine Drive',
    cityId: 'mumbai',
    image: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&q=80&w=800',
    description: 'Premium photography with the iconic Mumbai skyline background.',
    features: ['Sunset Shots', 'Candid Specialist', 'Drone Coverage'],
    isAvailable: true
  },
  {
    id: '3',
    name: 'Delhi Durbar Catering',
    category: ServiceCategory.CATERING,
    price: 800,
    rating: 4.7,
    reviewsCount: 210,
    location: 'Connaught Place',
    cityId: 'delhi',
    image: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&q=80&w=800',
    description: 'Authentic North Indian multi-cuisine catering service.',
    features: ['Live Counters', 'Veg & Non-Veg', 'Customizable Menu'],
    isAvailable: true
  },
  {
    id: '4',
    name: 'Royal Heritage Palace',
    category: ServiceCategory.VENUE,
    price: 85000,
    rating: 4.9,
    reviewsCount: 67,
    location: 'Amer Road',
    cityId: 'jaipur',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=800',
    description: 'Experience a royal wedding in the heart of the Pink City.',
    features: ['Historical Decor', 'Elephant Welcome', 'Royal Suites'],
    isAvailable: false
  },
  {
    id: '5',
    name: 'Howrah Bridge Events',
    category: ServiceCategory.DECORATION,
    price: 30000,
    rating: 4.6,
    reviewsCount: 88,
    location: 'Park Street',
    cityId: 'kolkata',
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&q=80&w=800',
    description: 'Traditional and artistic event decorations inspired by Bengali culture.',
    features: ['Floral Themes', 'Artistic Alpona', 'Thematic Lighting'],
    isAvailable: true
  },
  {
    id: '6',
    name: 'Coastal Bliss Photography',
    category: ServiceCategory.PHOTOGRAPHY,
    price: 12000,
    rating: 4.8,
    reviewsCount: 54,
    location: 'RK Beach',
    cityId: 'vishakapatnam',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800',
    description: 'Capture your memories by the bay with our expert beach photographers.',
    features: ['Beach Shoots', 'Outdoor Lighting', 'Quick Delivery'],
    isAvailable: true
  },
  {
    id: '7',
    name: 'Palace View Caterers',
    category: ServiceCategory.CATERING,
    price: 650,
    rating: 4.5,
    reviewsCount: 92,
    location: 'Siddhartha Layout',
    cityId: 'mysore',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800',
    description: 'Delicious Mysore specialty cuisines and South Indian delights.',
    features: ['Mysore Pak Specialist', 'Banana Leaf Service', 'Pure Veg Options'],
    isAvailable: true
  },
  {
    id: '8',
    name: 'Cyber City DJ Beats',
    category: ServiceCategory.MUSIC,
    price: 15000,
    rating: 4.9,
    reviewsCount: 312,
    location: 'Cyber Hub',
    cityId: 'gurgaon',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=800',
    description: 'Top-tier sound systems and energetic performance for corporate events.',
    features: ['Pioneer Gear', 'LED Stage', 'Request System'],
    isAvailable: true
  },
  {
    id: '9',
    name: 'Green Field Meadows',
    category: ServiceCategory.VENUE,
    price: 35000,
    rating: 4.7,
    reviewsCount: 45,
    location: 'Whitefield',
    cityId: 'bangalore',
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80&w=800',
    description: 'Beautiful open-air meadows for intimate garden parties.',
    features: ['Open Sky', 'Pet Friendly', 'Parking Space'],
    isAvailable: true
  },
  {
    id: '10',
    name: 'Vintage Decor Studio',
    category: ServiceCategory.DECORATION,
    price: 18000,
    rating: 4.4,
    reviewsCount: 28,
    location: 'Banjara Hills',
    cityId: 'hyderabad',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=800',
    description: 'Rustic and vintage-themed decorations for classic events.',
    features: ['Antiques', 'Edison Bulbs', 'Floral Arch'],
    isAvailable: true
  },
  {
    id: '11',
    name: 'Elite Event Planners',
    category: ServiceCategory.PLANNER,
    price: 50000,
    rating: 5.0,
    reviewsCount: 15,
    location: 'Koramangala',
    cityId: 'bangalore',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=800',
    description: 'Boutique planners who handle everything from concept to cleanup.',
    features: ['Full Planning', 'Vendor Liaison', 'Timeline Mgmt'],
    isAvailable: true
  },
  {
    id: '12',
    name: 'High Note Live Band',
    category: ServiceCategory.MUSIC,
    price: 25000,
    rating: 4.8,
    reviewsCount: 88,
    location: 'Indiranagar',
    cityId: 'bangalore',
    image: 'https://images.unsplash.com/photo-1493225255756-d9584f8606e9?auto=format&fit=crop&q=80&w=800',
    description: 'A multi-genre live band that guarantees a packed dance floor.',
    features: ['Bilingual Vocals', 'Full Kit', 'Standard Lights'],
    isAvailable: true
  }
];

export const CATEGORIES = [
  { id: ServiceCategory.VENUE, label: 'Venues', icon: '🏛️' },
  { id: ServiceCategory.PHOTOGRAPHY, label: 'Photography', icon: '📸' },
  { id: ServiceCategory.CATERING, label: 'Catering', icon: '🍲' },
  { id: ServiceCategory.DECORATION, label: 'Decor', icon: '✨' },
  { id: ServiceCategory.MUSIC, label: 'Music', icon: '🎸' },
  { id: ServiceCategory.PLANNER, label: 'Planners', icon: '📋' }
];
